"""Install a local Capacitor AudioFocus plugin into the Android app module.

Used so TTS can pause/duck background music (Android audio focus). The community
TextToSpeech plugin does not request focus on its own.
"""

from __future__ import annotations

import re
from pathlib import Path

__all__ = [
    "find_main_activity",
    "install_audio_focus_plugin",
]

_PLUGIN_CLASS = "AudioFocusPlugin"
_PLUGIN_NAME = "AudioFocus"


def find_main_activity(android_root: Path) -> Path | None:
    """Return ``MainActivity.java`` / ``.kt`` under the Android app module."""
    app_src = android_root / "app" / "src" / "main"
    if not app_src.is_dir():
        return None
    for path in app_src.rglob("MainActivity.java"):
        return path
    for path in app_src.rglob("MainActivity.kt"):
        return path
    return None


def _package_name(main_activity: Path) -> str | None:
    text = main_activity.read_text(encoding="utf-8")
    match = re.search(r"^\s*package\s+([\w.]+)\s*;?", text, flags=re.MULTILINE)
    return match.group(1) if match else None


def _plugin_java_source(package: str) -> str:
    return f"""package {package};

import android.content.Context;
import android.media.AudioAttributes;
import android.media.AudioFocusRequest;
import android.media.AudioManager;
import android.os.Build;
import android.os.Handler;
import android.os.Looper;

import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;

/**
 * Requests transient audio focus so TTS can pause/duck other apps (music, etc.).
 * Generated by reflex-capacitor — do not edit by hand.
 *
 * Uses USAGE_MEDIA (not ASSISTANT): QQ Music / NetEase often ignore assistant focus.
 */
@CapacitorPlugin(name = "{_PLUGIN_NAME}")
public class {_PLUGIN_CLASS} extends Plugin {{
    private AudioManager audioManager;
    private AudioFocusRequest focusRequest;
    private final Handler mainHandler = new Handler(Looper.getMainLooper());
    private final AudioManager.OnAudioFocusChangeListener focusChangeListener =
        focusChange -> {{
            /* no-op: TTS owns the focus for the utterance duration */
        }};

    @Override
    public void load() {{
        audioManager = (AudioManager) getContext().getSystemService(Context.AUDIO_SERVICE);
    }}

    @PluginMethod
    public void request(PluginCall call) {{
        if (audioManager == null) {{
            call.reject("audio_manager_missing");
            return;
        }}
        // Run on main thread — some OEMs ignore focus requests from bridge threads.
        mainHandler.post(() -> {{
            try {{
                resolveRequest(call);
            }} catch (Exception e) {{
                call.reject("audio_focus_failed", e);
            }}
        }});
    }}

    private void resolveRequest(PluginCall call) {{
        // Abandon any previous request so we do not stack listeners.
        abandonFocusQuietly();

        String mode = call.getString("mode", "pause");
        int durationHint;
        if ("duck".equalsIgnoreCase(mode)) {{
            durationHint = AudioManager.AUDIOFOCUS_GAIN_TRANSIENT_MAY_DUCK;
        }} else if ("exclusive".equalsIgnoreCase(mode) || "pause".equalsIgnoreCase(mode)) {{
            // EXCLUSIVE asks others to pause (not merely duck). Better for QQ Music.
            durationHint = AudioManager.AUDIOFOCUS_GAIN_TRANSIENT_EXCLUSIVE;
        }} else {{
            durationHint = AudioManager.AUDIOFOCUS_GAIN_TRANSIENT;
        }}

        int result;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {{
            AudioAttributes attrs =
                new AudioAttributes.Builder()
                    .setUsage(AudioAttributes.USAGE_MEDIA)
                    .setContentType(AudioAttributes.CONTENT_TYPE_SPEECH)
                    .build();
            AudioFocusRequest.Builder builder =
                new AudioFocusRequest.Builder(durationHint)
                    .setAudioAttributes(attrs)
                    .setAcceptsDelayedFocusGain(false)
                    .setOnAudioFocusChangeListener(focusChangeListener, mainHandler);
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {{
                builder.setForceDucking(false);
            }}
            focusRequest = builder.build();
            result = audioManager.requestAudioFocus(focusRequest);
        }} else {{
            result =
                audioManager.requestAudioFocus(
                    focusChangeListener, AudioManager.STREAM_MUSIC, durationHint);
        }}

        JSObject ret = new JSObject();
        ret.put("granted", result == AudioManager.AUDIOFOCUS_REQUEST_GRANTED);
        ret.put("result", result);
        ret.put("mode", mode);
        call.resolve(ret);
    }}

    @PluginMethod
    public void abandon(PluginCall call) {{
        mainHandler.post(() -> {{
            abandonFocusQuietly();
            JSObject ret = new JSObject();
            ret.put("ok", true);
            call.resolve(ret);
        }});
    }}

    private void abandonFocusQuietly() {{
        if (audioManager == null) {{
            return;
        }}
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O && focusRequest != null) {{
            audioManager.abandonAudioFocusRequest(focusRequest);
            focusRequest = null;
        }} else {{
            audioManager.abandonAudioFocus(focusChangeListener);
        }}
    }}
}}
"""


def _ensure_main_activity_registers(main_activity: Path) -> bool:
    """Ensure MainActivity registers AudioFocusPlugin before super.onCreate. Returns True if changed."""
    text = main_activity.read_text(encoding="utf-8")
    if _PLUGIN_CLASS in text and "registerPlugin" in text:
        return False

    if main_activity.suffix == ".kt":
        patched = text
        if "import android.os.Bundle" not in patched:
            patched = patched.replace(
                "import com.getcapacitor.BridgeActivity",
                "import android.os.Bundle\nimport com.getcapacitor.BridgeActivity",
                1,
            )
        if "override fun onCreate" in patched:
            if f"registerPlugin({_PLUGIN_CLASS}::class.java)" not in patched:
                patched = re.sub(
                    r"(override fun onCreate\s*\([^)]*\)\s*\{)",
                    rf"\1\n        registerPlugin({_PLUGIN_CLASS}::class.java)",
                    patched,
                    count=1,
                )
        else:
            # Empty BridgeActivity subclass — add onCreate
            with_body = re.sub(
                r"(class\s+MainActivity\s*:\s*BridgeActivity\s*\(\s*\)\s*\{)",
                rf"\1\n    override fun onCreate(savedInstanceState: Bundle?) {{\n"
                rf"        registerPlugin({_PLUGIN_CLASS}::class.java)\n"
                rf"        super.onCreate(savedInstanceState)\n    }}\n",
                patched,
                count=1,
            )
            if with_body != patched:
                patched = with_body
            else:
                # No body braces: `class MainActivity : BridgeActivity()`
                patched = re.sub(
                    r"(class\s+MainActivity\s*:\s*BridgeActivity\s*\(\s*\))",
                    rf"\1 {{\n    override fun onCreate(savedInstanceState: Bundle?) {{\n"
                    rf"        registerPlugin({_PLUGIN_CLASS}::class.java)\n"
                    rf"        super.onCreate(savedInstanceState)\n    }}\n}}",
                    patched,
                    count=1,
                )
        if f"registerPlugin({_PLUGIN_CLASS}::class.java)" not in patched:
            return False
        if patched != text:
            main_activity.write_text(patched, encoding="utf-8")
            return True
        return False

    # Java MainActivity
    patched = text
    if "import android.os.Bundle;" not in patched:
        patched = patched.replace(
            "import com.getcapacitor.BridgeActivity;",
            "import android.os.Bundle;\nimport com.getcapacitor.BridgeActivity;",
            1,
        )

    if "void onCreate" in patched:
        if f"registerPlugin({_PLUGIN_CLASS}.class)" not in patched:
            patched = re.sub(
                r"(protected\s+void\s+onCreate\s*\([^)]*\)\s*\{|public\s+void\s+onCreate\s*\([^)]*\)\s*\{)",
                rf"\1\n        registerPlugin({_PLUGIN_CLASS}.class);",
                patched,
                count=1,
            )
    else:
        # Empty BridgeActivity subclass — add onCreate
        patched = re.sub(
            r"(public\s+class\s+MainActivity\s+extends\s+BridgeActivity\s*\{)",
            rf"\1\n    @Override\n    public void onCreate(Bundle savedInstanceState) {{\n"
            rf"        registerPlugin({_PLUGIN_CLASS}.class);\n"
            rf"        super.onCreate(savedInstanceState);\n    }}\n",
            patched,
            count=1,
        )

    if patched == text:
        return False
    main_activity.write_text(patched, encoding="utf-8")
    return True


def install_audio_focus_plugin(android_root: Path | str) -> list[str]:
    """Write ``AudioFocusPlugin`` and register it from MainActivity.

    Returns:
        Human-readable list of actions taken (empty if Android tree missing).
    """
    root = Path(android_root)
    main_activity = find_main_activity(root)
    if main_activity is None:
        return []

    package = _package_name(main_activity)
    if not package:
        return []

    actions: list[str] = []
    plugin_path = main_activity.parent / f"{_PLUGIN_CLASS}.java"
    source = _plugin_java_source(package)
    if not plugin_path.is_file() or plugin_path.read_text(encoding="utf-8") != source:
        plugin_path.write_text(source, encoding="utf-8")
        actions.append(f"wrote {plugin_path.name}")

    if _ensure_main_activity_registers(main_activity):
        actions.append(f"registered plugin in {main_activity.name}")

    return actions
