"""Type stubs for reflex_capacitor.bridge.api."""

from typing import Any, Literal

import reflex as rx

ImpactStyle = Literal["HEAVY", "MEDIUM", "LIGHT"]
NotificationStyle = Literal["SUCCESS", "WARNING", "ERROR"]
StatusBarStyle = Literal["DARK", "LIGHT", "DEFAULT"]
ToastDuration = Literal["short", "long"]

def notify(title: str, body: str = "") -> rx.event.EventSpec: ...
def toast(text: str, *, duration: ToastDuration = "short") -> rx.event.EventSpec: ...
def haptics_impact(*, style: ImpactStyle = "MEDIUM", callback: Any = None) -> rx.event.EventSpec: ...
def haptics_notification(*, type: NotificationStyle = "SUCCESS", callback: Any = None) -> rx.event.EventSpec: ...
def haptics_vibrate(*, duration_ms: int = 300, callback: Any = None) -> rx.event.EventSpec: ...
def share(
    *,
    title: str | None = None,
    text: str | None = None,
    url: str | None = None,
    dialog_title: str | None = None,
) -> rx.event.EventSpec: ...
def clipboard_write(text: str) -> rx.event.EventSpec: ...
def clipboard_read(callback: Any) -> rx.event.EventSpec: ...
def status_bar_set_style(*, style: StatusBarStyle = "DARK") -> rx.event.EventSpec: ...
def status_bar_hide() -> rx.event.EventSpec: ...
def status_bar_show() -> rx.event.EventSpec: ...
def splash_hide() -> rx.event.EventSpec: ...
def device_info(callback: Any) -> rx.event.EventSpec: ...
def network_status(callback: Any) -> rx.event.EventSpec: ...
def app_exit() -> rx.event.EventSpec: ...
def diagnostics(callback: Any) -> rx.event.EventSpec: ...
def platform_info(callback: Any) -> rx.event.EventSpec: ...
def bridge_logs(limit: int = 50, callback: Any = None) -> rx.event.EventSpec: ...
def clear_logs() -> rx.event.EventSpec: ...
def pref_set(key: str, value: str, *, callback: Any = None) -> rx.event.EventSpec: ...
def pref_get(key: str, callback: Any) -> rx.event.EventSpec: ...
def take_photo(
    callback: Any, *, quality: int = 90, save_to_gallery: bool = False
) -> rx.event.EventSpec: ...
def pick_images(callback: Any, *, limit: int = 1, quality: int = 90) -> rx.event.EventSpec: ...
def get_current_position(callback: Any, *, enable_high_accuracy: bool = False, timeout_ms: int = 30000) -> rx.event.EventSpec: ...
def keyboard_show(*, callback: Any = None) -> rx.event.EventSpec: ...
def keyboard_hide(*, callback: Any = None) -> rx.event.EventSpec: ...
def browser_open(url: str, *, callback: Any = None) -> rx.event.EventSpec: ...
def fs_write(
    path: str, data: str, *, directory: str = "DATA", callback: Any = None
) -> rx.event.EventSpec: ...
def fs_read(path: str, callback: Any, *, directory: str = "DATA") -> rx.event.EventSpec: ...
def start_recording(
    *,
    directory: str | None = None,
    sub_directory: str | None = None,
    callback: Any = None,
) -> rx.event.EventSpec: ...
def stop_recording(callback: Any) -> rx.event.EventSpec: ...
def play_recording(
    *,
    data_url: str | None = None,
    path: str | None = None,
    callback: Any = None,
) -> rx.event.EventSpec: ...
def stop_playback(*, callback: Any = None) -> rx.event.EventSpec: ...
def recording_status(callback: Any) -> rx.event.EventSpec: ...
def speak(
    text: str,
    *,
    lang: str = "zh-CN",
    rate: float = 1.0,
    pitch: float = 1.0,
    volume: float = 1.0,
    callback: Any = None,
) -> rx.event.EventSpec: ...
def stop_speak(*, callback: Any = None) -> rx.event.EventSpec: ...
def invoke(
    plugin: str, method: str, args: dict[str, Any] | None = None, *, callback: Any = None
) -> rx.event.EventSpec: ...
def setup_native_listeners(
    *, back_button: Literal["emit", "exit", "history"] = "emit", callback: Any = None
) -> rx.event.EventSpec: ...
def poll_native_events(callback: Any) -> rx.event.EventSpec: ...
def push_register(*, callback: Any = None) -> rx.event.EventSpec: ...
def push_check_permissions(*, callback: Any = None) -> rx.event.EventSpec: ...
def push_request_permissions(*, callback: Any = None) -> rx.event.EventSpec: ...
